# Generated by Django 4.1.6 on 2023-05-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tipo_tramite_nombre_padre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_tramite',
            old_name='id_servicio',
            new_name='id_proceso',
        ),
    ]
