# Generated by Django 4.1 on 2022-09-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Persona')),
                ('genero', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('acceptance_tm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
